# ASCII art brought to you by:
# http://patorjk.com/software/taag/#p=display&f=Star%20Wars&t=Type%20Something%20

stages:
  - build
  - deploy

variables:
  TAG: $CI_COMMIT_SHA
  BRANCH: $CI_COMMIT_REF_SLUG
  REGISTRY: ci.tno.nl
  IMAGE_BASE: ci.tno.nl/multimodelling/mmvib-registry

image: docker:20.10

services:
  - docker:20.10-dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $REGISTRY

# ______    __    __   __   __       _______
#|   _  \  |  |  |  | |  | |  |     |       \
#|  |_)  | |  |  |  | |  | |  |     |  .--.  |
#|   _  <  |  |  |  | |  | |  |     |  |  |  |
#|  |_)  | |  `--'  | |  | |  `----.|  '--'  |
#|______/   \______/  |__| |_______||_______/

build:
  stage: build
  variables:
    IMAGE: $IMAGE_BASE/api
  script:
    - docker pull $IMAGE:$BRANCH || true
    - docker build --build-arg git_commit=$TAG . -f Dockerfile --cache-from $IMAGE:$BRANCH -t $IMAGE:$TAG -t $IMAGE:$BRANCH
    - docker push $IMAGE:$TAG
    - docker push $IMAGE:$BRANCH

# _______   _______ .______    __        ______   ____    ____
#|       \ |   ____||   _  \  |  |      /  __  \  \   \  /   /
#|  .--.  ||  |__   |  |_)  | |  |     |  |  |  |  \   \/   /
#|  |  |  ||   __|  |   ___/  |  |     |  |  |  |   \_    _/
#|  '--'  ||  |____ |  |      |  `----.|  `--'  |     |  |
#|_______/ |_______|| _|      |_______| \______/      |__|

push-latest:
  stage: deploy
  variables:
    IMAGE: $IMAGE_BASE/api
  script:
    - docker pull $IMAGE:$TAG
    - docker tag $IMAGE:$TAG $IMAGE:latest
    - docker push $IMAGE:latest
