version: "3.2"

services:
  mmvib-registry:
    build: .
    volumes:
      - .:/code
    command: ["gunicorn", "--reload", "tno.mmvib_registry.main:app", "-t 300", "-w 1", "-b :9200"]
    ports:
      - "9200:9200"
    env_file:
      - ".env.docker"
    networks:
      - mmvib-net

networks:
  mmvib-net:
    external:
      name: mmvib-net