version: "3.8"

services:
  postgis:
    image: postgis/postgis:latest
    env_file:
      - ".env.docker"
    ports:
      - "9232:5432"
    volumes:
      - postgis-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadminer:
    image: adminer
    environment:
      - ADMINER_DESIGN=lucas-sandery
      - ADMINER_DEFAULT_SERVER=postgis
    ports:
      - "9280:8080"

volumes:
  postgis-data:
