version: "3.8"

services:
  postgres:
    image: postgres:15
    env_file:
      - ".env.docker"
    ports:
      - "9932:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-modelregistry}
      - POSTGRES_USER=${POSTGRES_DB_USER:-modelregistry}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWD:-modelregistry}

  pgadminer:
    image: adminer
    environment:
      - ADMINER_DESIGN=lucas-sandery
      - ADMINER_DEFAULT_SERVER=postgres
    ports:
      - "9980:8080"

volumes:
  postgres-data:
